# ./docker/php/Dockerfile-prod
FROM php:7.4-fpm

RUN docker-php-ext-install pdo_mysql

RUN pecl install apcu

RUN apt-get update && \
apt-get install -y \
openssl bash wget \
libzip-dev zip && docker-php-ext-install zip

RUN docker-php-ext-enable apcu

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
    && php composer-setup.php --filename=composer \
    && php -r "unlink('composer-setup.php');" \
    && mv composer /usr/local/bin/composer

COPY ./docker/php/memory-limit-php.ini /usr/local/etc/php/conf.d/memory-limit-php.ini

WORKDIR /usr/src/app

COPY . ./
RUN composer install --ignore-platform-reqs --no-scripts --no-autoloader
RUN composer dump-autoload --optimize

RUN cp .env.example .env