controllers:
  resource: ../../src/Controller/
  type: annotation
  host:
    - "*.quizx.com.br"
    - "quizx.com.br"
    - "localhost"

controllers_aluno:
  resource: ../../src/Controller/Aluno/Quiz/
  type: annotation

controllers_api:
  resource: ../../src/Controller/Api/
  type: annotation
  prefix: /api/v1

kernel:
  resource: ../../src/Kernel.php
  type: annotation
