monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: critical
      handler: deduplicated
    deduplicated:
      type: deduplication
      handler: symfony_mailer
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]

    symfony_mailer:
      type: service
      id: symfony_mailer_service
