# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
      - "../src/Tests/"

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]

  app.event.request_translator:
    class: App\EventListener\Translate
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 256 }

  App\Repository\:
    resource: "../src/Repository"
    autowire: true
    tags: ["doctrine.repository_service"]

  symfony_mailer_service_template:
    class: Symfony\Component\Mime\Email
    calls:
      - ["from", ["no-reply@quizx.com.br"]]
      - ["to", ["ewerton.code@gmail.com"]]
      - ["subject", ["Logs erro QuizX"]]

  symfony_mailer_service:
    class: Symfony\Bridge\Monolog\Handler\MailerHandler
    arguments:
      - "@mailer.mailer"
      - "@symfony_mailer_service_template"
      - !php/const Monolog\Logger::CRITICAL # log level
      - true # bubble
